/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package memberDASHBOARD;

import config.UserSession;
import javax.swing.JOptionPane;
import main.landing;
import main.login;
import static sun.security.jgss.GSSUtil.login;

/**
 *
 * @author Lloyd's PC
 */
public class editprofile extends javax.swing.JInternalFrame { 

  public editprofile() {
    // 1. super MUST be first
    super("Edit Profile", false, false, false, false);

   // 2. Check if a session exists
if (UserSession.getInstance().getFullName() == null) {
    JOptionPane.showMessageDialog(null, "No active session. Redirecting to Login...");
    
    // 3. Open the Landing Page
    main.landing landingPage = new main.landing(); 
    landingPage.setVisible(true);
    
    // 4. THIS PART FIXES THE 2 WINDOWS:
    // We find the window that called this constructor and close it
    java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);
    if (win != null) {
        win.setVisible(false); // Hide it immediately
        win.dispose();         // Destroy it
    }
    
    return; 
}

    // Only runs if the session check passes
    initComponents();
    
    // UI Cleanup (Removes the internal frame headers)
    this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    javax.swing.plaf.basic.BasicInternalFrameUI bi = (javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI();
    bi.setNorthPane(null);
    
    displayUserDetails();
    id.setEditable(false);
}
   private void displayUserDetails() {
   config.config conf = new config.config();
        int u_id = UserSession.getInstance().getId();
        
        try (java.sql.Connection conn = conf.connectDB();
             java.sql.Statement stmt = conn.createStatement();
             java.sql.ResultSet rs = stmt.executeQuery("SELECT * FROM users_tbl WHERE u_id = " + u_id)) {
            
            if (rs.next()) {
                id.setText(rs.getString("u_id"));
                fullname.setText(rs.getString("full_name"));
                email.setText(rs.getString("email"));
                phone.setText(rs.getString("phonenumber"));
            }
        } catch (java.sql.SQLException e) {
            System.out.println("Error loading profile: " + e.getMessage());
        }
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        editprofile = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        fullname = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        editpro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(39, 41, 46));
        jPanel1.setPreferredSize(new java.awt.Dimension(910, 610));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 440, -1, -1));

        editprofile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile13.png"))); // NOI18N
        jPanel1.add(editprofile, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        id.setBackground(new java.awt.Color(39, 41, 46));
        id.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        id.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "id", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 2, 14), new java.awt.Color(102, 255, 102))); // NOI18N
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 270, 80));

        fullname.setBackground(new java.awt.Color(39, 41, 46));
        fullname.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        fullname.setForeground(new java.awt.Color(255, 255, 255));
        fullname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fullname.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fullname", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 2, 14), new java.awt.Color(102, 255, 102))); // NOI18N
        fullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameActionPerformed(evt);
            }
        });
        jPanel1.add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 270, 80));

        phone.setBackground(new java.awt.Color(39, 41, 46));
        phone.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        phone.setForeground(new java.awt.Color(255, 255, 255));
        phone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        phone.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "phone", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 2, 14), new java.awt.Color(102, 255, 102))); // NOI18N
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 270, 80));

        email.setBackground(new java.awt.Color(39, 41, 46));
        email.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        email.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "email", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 2, 14), new java.awt.Color(102, 255, 102))); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 270, 80));

        editpro.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        editpro.setForeground(new java.awt.Color(255, 255, 255));
        editpro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edits.png"))); // NOI18N
        editpro.setText("Edit Profile");
        editpro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editproMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editproMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editproMouseExited(evt);
            }
        });
        jPanel1.add(editpro, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void editproMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editproMouseClicked
 String name = fullname.getText().trim();
    String userEmail = email.getText().trim();
    String userPhone = phone.getText().trim();

    // 1. Validation Check
    if (name.isEmpty() || userEmail.isEmpty() || userPhone.isEmpty()) {
        JOptionPane.showMessageDialog(null, "All fields are required!");
        return;
    }

    config.config conf = new config.config();
    UserSession sess = UserSession.getInstance();
    
    try {
        int userId = sess.getId(); // Use the session ID directly for security

        String sql = "UPDATE users_tbl SET full_name = ?, email = ?, phonenumber = ? WHERE u_id = ?";
        
        // Use your config helper to execute the update
        conf.addRecord(sql, name, userEmail, userPhone, userId);
        
        // 2. Update the Session object so the Dashboard reflects changes immediately
        sess.setFullName(name);
        sess.setEmail(userEmail);

        JOptionPane.showMessageDialog(null, "Profile Updated Successfully!");
        
        // 3. Optional: If you want the dashboard to refresh the text immediately:
        // ((memberdashboard)javax.swing.SwingUtilities.getWindowAncestor(this)).displayUserInfo();

        this.dispose(); // Close the internal frame

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Update Error: " + e.getMessage());
    }
    }//GEN-LAST:event_editproMouseClicked

    private void editproMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editproMouseEntered
        editpro.setForeground(new java.awt.Color(170, 231, 37));
    }//GEN-LAST:event_editproMouseEntered

    private void editproMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editproMouseExited
        editpro.setForeground(new java.awt.Color(255, 255, 255)); // White
    }//GEN-LAST:event_editproMouseExited

    /**
     * @param args the command line arguments
     */
  public static void main(String args[]) {
    /* Set Nimbus look and feel */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        ex.printStackTrace();
    }

    /* Create a temporary JFrame to host the InternalFrame for testing */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            // CHECK SESSION HERE BEFORE CREATING THE WINDOW
            if (config.UserSession.getInstance().getFullName() == null) {
                JOptionPane.showMessageDialog(null, "No active session. Redirecting to Login...");
                main.landing landingPage = new main.landing();
                landingPage.setVisible(true);
                return; // STOP HERE so 'testFrame' is never created
            }

            // This part only runs if a session exists
            javax.swing.JFrame testFrame = new javax.swing.JFrame("Internal Frame Preview");
            javax.swing.JDesktopPane desktop = new javax.swing.JDesktopPane();
            
            editprofile internalFrame = new editprofile();
            internalFrame.setSize(910, 610); 
            internalFrame.setVisible(true);
            
            desktop.add(internalFrame);
            testFrame.add(desktop);
            testFrame.setSize(920, 650);
            testFrame.setLocationRelativeTo(null);
            testFrame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
            testFrame.setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel editpro;
    private javax.swing.JLabel editprofile;
    public javax.swing.JTextField email;
    public javax.swing.JTextField fullname;
    public javax.swing.JTextField id;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField phone;
    // End of variables declaration//GEN-END:variables
}
