/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package memberDASHBOARD;

import config.config;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableCellRenderer;
/**
 *
 * @author Lloyd's PC
 */
public class viewclasses extends javax.swing.JInternalFrame { 

    public viewclasses() {
       initComponents();
    displayClasses(); // Pulls the data immediately when the page opens
    
    // 1. Remove Title Bar and Borders
    this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
    bi.setNorthPane(null);
    
    // 2. Make ScrollPane (viewclasses) transparent
    classestable.setOpaque(false);
    viewclasses.setOpaque(false);
    viewclasses.getViewport().setOpaque(false);
    viewclasses.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    
    // 3. Style Table Cells
    DefaultTableCellRenderer renderer = (DefaultTableCellRenderer)classestable.getDefaultRenderer(Object.class);
    renderer.setOpaque(false);
    classestable.setBackground(new java.awt.Color(39, 41, 46));
    
    // 4. Force Header Styling (Matches your Neon Theme)
    classestable.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer() {
        @Override
        public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            setBackground(new java.awt.Color(39, 41, 46)); 
            setForeground(new java.awt.Color(170, 231, 37)); 
            setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
            setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 60, 60)));
            return this;
        }
    });
    }
 public void displayClasses() {
    config con = new config();
    // This pulls all columns from your tbl_classes. 
    // Make sure 'tbl_classes' is the exact name in your database.
    String sql = "SELECT * FROM tbl_classes"; 
    con.displayData(sql, classestable);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BACKBOTTOMEMBERDASH = new javax.swing.JLabel();
        viewclasses = new javax.swing.JScrollPane();
        classestable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(39, 41, 46));
        jPanel1.setPreferredSize(new java.awt.Dimension(910, 610));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 440, -1, -1));

        BACKBOTTOMEMBERDASH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        BACKBOTTOMEMBERDASH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BACKBOTTOMEMBERDASHMouseClicked(evt);
            }
        });
        jPanel1.add(BACKBOTTOMEMBERDASH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, -1, -1));

        classestable.setBackground(new java.awt.Color(39, 41, 46));
        classestable.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        classestable.setForeground(new java.awt.Color(170, 231, 37));
        classestable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        classestable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        classestable.setGridColor(new java.awt.Color(153, 153, 153));
        classestable.setPreferredSize(new java.awt.Dimension(686, 514));
        classestable.setSelectionBackground(new java.awt.Color(204, 204, 204));
        classestable.setSelectionForeground(new java.awt.Color(204, 204, 204));
        viewclasses.setViewportView(classestable);

        jPanel1.add(viewclasses, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 690, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BACKBOTTOMEMBERDASHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKBOTTOMEMBERDASHMouseClicked
// 1. Get the dashboard window
    javax.swing.JFrame topFrame = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
    
    // 2. Create a fresh instance of the dashboard
    DASHBOARDS.memberdashboard md = new DASHBOARDS.memberdashboard();
    md.setVisible(true);
    
    // 3. Close the current window
    topFrame.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_BACKBOTTOMEMBERDASHMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewclasses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewclasses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewclasses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewclasses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewclasses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BACKBOTTOMEMBERDASH;
    private javax.swing.JTable classestable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane viewclasses;
    // End of variables declaration//GEN-END:variables
}
