/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalPages;
import config.config;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.security.MessageDigest;
import java.nio.charset.StandardCharsets;
import java.sql.DriverManager;
import java.sql.SQLException;
import static sun.security.jgss.GSSUtil.login;

public class Memberpage extends javax.swing.JInternalFrame {

    
    public Memberpage() {
        initComponents();
        
    // 1. Set the background of the frame's container
    this.getContentPane().setBackground(new java.awt.Color(33, 37, 41));
    
    // 2. Set the background of jPanel2 (the main container)
    jPanel2.setBackground(new java.awt.Color(33, 37, 41));
    
    // 3. Remove the border of the internal frame to make it blend in
    this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        memberfn = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        memberem = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        mempass = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel7.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLabel7.setText("Email Address");

        jTextField5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 450));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(39, 41, 46));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(170, 231, 37));
        jLabel13.setText("Full name:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        memberfn.setBackground(new java.awt.Color(39, 41, 46));
        memberfn.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        memberfn.setForeground(new java.awt.Color(255, 255, 255));
        memberfn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        memberfn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberfnActionPerformed(evt);
            }
        });
        jPanel2.add(memberfn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 390, 50));

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(170, 231, 37));
        jLabel14.setText("Email Address:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        memberem.setBackground(new java.awt.Color(39, 41, 46));
        memberem.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        memberem.setForeground(new java.awt.Color(255, 255, 255));
        memberem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        memberem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberemActionPerformed(evt);
            }
        });
        jPanel2.add(memberem, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 390, 50));

        jLabel15.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(170, 231, 37));
        jLabel15.setText("Phone number:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        phone.setBackground(new java.awt.Color(39, 41, 46));
        phone.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        phone.setForeground(new java.awt.Color(255, 255, 255));
        phone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        jPanel2.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 390, 50));

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(170, 231, 37));
        jLabel16.setText("Password:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        mempass.setBackground(new java.awt.Color(39, 41, 46));
        mempass.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        mempass.setForeground(new java.awt.Color(255, 255, 255));
        mempass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        mempass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mempassActionPerformed(evt);
            }
        });
        jPanel2.add(mempass, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 390, 50));

        jButton2.setBackground(new java.awt.Color(170, 231, 37));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(39, 41, 46));
        jButton2.setText("Register");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 180, 50));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/weightlifter.png"))); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 150));
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(170, 231, 37));
        jLabel3.setText("LOGIN NOW");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void memberfnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberfnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memberfnActionPerformed

    private void memberemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memberemActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void mempassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mempassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mempassActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    String f_name = memberfn.getText().trim();
    String u_email = memberem.getText().trim();
    String u_phone = phone.getText().trim();
    String u_pass = new String(mempass.getPassword());

    // 1. Validation check
    if (f_name.isEmpty() || u_email.isEmpty() || u_pass.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all required fields!");
        return;
    }

    try {
        config conf = new config(); 
        Connection conn = conf.connectDB(); 

        // 2. SQL String
        String sql = "INSERT INTO users_tbl (full_name, email, phonenumber, password, u_type) VALUES (?, ?, ?, ?, ?)";
        PreparedStatement pst = conn.prepareStatement(sql);

        // 3. Hashing the password
        // Use the method from your config class to keep it consistent with Login
        String hashedPass = conf.hashPassword(u_pass); 

        pst.setString(1, f_name);
        pst.setString(2, u_email);
        pst.setString(3, u_phone);
        pst.setString(4, hashedPass); // Hashed password goes here
        pst.setString(5, "Member");

        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Member Successfully Registered!");

        // 4. Clear the fields
        memberfn.setText("");
        memberem.setText("");
        phone.setText("");
        mempass.setText("");

        pst.close();
        conn.close();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        login r = new login();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked
private String hashPassword(String password) {
    try {
        MessageDigest md = MessageDigest.getInstance("SHA-256");
        byte[] hashedBytes = md.digest(password.getBytes(StandardCharsets.UTF_8));

        StringBuilder sb = new StringBuilder();
        for (byte b : hashedBytes) {
            sb.append(String.format("%02x", b));
        }
        return sb.toString();
    } catch (Exception e) {
        return null;
    }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField memberem;
    private javax.swing.JTextField memberfn;
    private javax.swing.JPasswordField mempass;
    private javax.swing.JTextField phone;
    // End of variables declaration//GEN-END:variables
}
