/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalPages;

import config.config;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import main.login;
import static sun.security.jgss.GSSUtil.login;

/**
 *
 * @author Lloyd's PC
 */
public class Trainerpage extends javax.swing.JInternalFrame {

    /**
     * Creates new form Trainerpage
     */
    public Trainerpage() {
        initComponents();
        
    // 1. Set the background of the frame's container
    this.getContentPane().setBackground(new java.awt.Color(33, 37, 41));
    
    // 2. Set the background of jPanel2 (the main container)
    jPanel2.setBackground(new java.awt.Color(33, 37, 41));
    jPanel1.setBackground(new java.awt.Color(33, 37, 41)); //This was (204, 204, 204) in your generated code!
    jPanel2.setBackground(new java.awt.Color(33, 37, 41));
    jPanel4.setBackground(new java.awt.Color(33, 37, 41));
    // 3. Remove the border of the internal frame to make it blend in
    this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        fullnametrainer = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        emailtrainer = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Bio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        passtrainer = new javax.swing.JPasswordField();
        phonetrainer1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        specialty = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(39, 41, 46));
        jPanel4.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(170, 231, 37));
        jLabel5.setText("Full name:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        fullnametrainer.setBackground(new java.awt.Color(39, 41, 46));
        fullnametrainer.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        fullnametrainer.setForeground(new java.awt.Color(255, 255, 255));
        fullnametrainer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        fullnametrainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnametrainerActionPerformed(evt);
            }
        });
        jPanel4.add(fullnametrainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 390, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(170, 231, 37));
        jLabel6.setText("Email Address:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        emailtrainer.setBackground(new java.awt.Color(39, 41, 46));
        emailtrainer.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        emailtrainer.setForeground(new java.awt.Color(255, 255, 255));
        emailtrainer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        emailtrainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtrainerActionPerformed(evt);
            }
        });
        jPanel4.add(emailtrainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 390, 50));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(170, 231, 37));
        jLabel8.setText("Phone number:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        Bio.setBackground(new java.awt.Color(39, 41, 46));
        Bio.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Bio.setForeground(new java.awt.Color(255, 255, 255));
        Bio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        Bio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BioActionPerformed(evt);
            }
        });
        jPanel4.add(Bio, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 390, 50));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(170, 231, 37));
        jLabel9.setText("Bio:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        jButton1.setBackground(new java.awt.Color(170, 231, 37));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(39, 41, 46));
        jButton1.setText("Register");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 180, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trainer11.png"))); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(170, 231, 37));
        jLabel10.setText("Password:");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, -1, -1));

        passtrainer.setBackground(new java.awt.Color(39, 41, 46));
        passtrainer.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        passtrainer.setForeground(new java.awt.Color(255, 255, 255));
        passtrainer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        passtrainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passtrainerActionPerformed(evt);
            }
        });
        jPanel4.add(passtrainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 390, 50));

        phonetrainer1.setBackground(new java.awt.Color(39, 41, 46));
        phonetrainer1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        phonetrainer1.setForeground(new java.awt.Color(255, 255, 255));
        phonetrainer1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        phonetrainer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonetrainer1ActionPerformed(evt);
            }
        });
        jPanel4.add(phonetrainer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 390, 50));

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(170, 231, 37));
        jLabel11.setText("Specialty:");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, -1, -1));

        specialty.setBackground(new java.awt.Color(39, 41, 46));
        specialty.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        specialty.setForeground(new java.awt.Color(255, 255, 255));
        specialty.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        specialty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialtyActionPerformed(evt);
            }
        });
        jPanel4.add(specialty, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 390, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(170, 231, 37));
        jLabel3.setText("LOGIN NOW");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, -1, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fullnametrainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnametrainerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnametrainerActionPerformed

    private void emailtrainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtrainerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtrainerActionPerformed

    private void BioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String f_name = fullnametrainer.getText().trim();
    String u_email = emailtrainer.getText().trim();
    String u_phone = phonetrainer1.getText().trim();
    String u_bio = Bio.getText().trim();
    String u_spec = specialty.getText().trim();
    String u_pass = new String(passtrainer.getPassword());

    // 1. Validation check
    if (f_name.isEmpty() || u_email.isEmpty() || u_pass.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all required fields!");
        return;
    }

    try {
        config conf = new config(); 
        Connection conn = conf.connectDB(); // Using your config for the connection
        conn.setAutoCommit(false); // Start transaction for multi-table insert

        // STEP 1: Insert into users_tbl (Hashing the password here)
        String sqlUser = "INSERT INTO users_tbl (full_name, email, phonenumber, password, u_type) VALUES (?, ?, ?, ?, ?)";
        PreparedStatement pstUser = conn.prepareStatement(sqlUser, java.sql.Statement.RETURN_GENERATED_KEYS);
        
        pstUser.setString(1, f_name);
        pstUser.setString(2, u_email);
        pstUser.setString(3, u_phone);
        pstUser.setString(4, conf.hashPassword(u_pass)); // CONSISTENT HASHING
        pstUser.setString(5, "Trainer");
        pstUser.executeUpdate();

        // Retrieve the generated u_id to link the trainer table
        java.sql.ResultSet rs = pstUser.getGeneratedKeys();
        int generatedId = 0;
        if (rs.next()) {
            generatedId = rs.getInt(1);
        }

        // STEP 2: Insert into tbl_trainers using the generated u_id
        String sqlTrainer = "INSERT INTO tbl_trainers (full_n, phone, bio, specialty, u_id) VALUES (?, ?, ?, ?, ?)";
        PreparedStatement pstTrainer = conn.prepareStatement(sqlTrainer);
        pstTrainer.setString(1, f_name);
        pstTrainer.setString(2, u_phone);
        pstTrainer.setString(3, u_bio);
        pstTrainer.setString(4, u_spec);
        pstTrainer.setInt(5, generatedId); 
        pstTrainer.executeUpdate();

        conn.commit(); // Save changes to both tables
        JOptionPane.showMessageDialog(this, "Trainer Registered Successfully!");

        // Clear fields
        fullnametrainer.setText("");
        emailtrainer.setText("");
        phonetrainer1.setText("");
        Bio.setText("");
        specialty.setText("");
        passtrainer.setText("");

        pstUser.close();
        pstTrainer.close();
        conn.close();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void passtrainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passtrainerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passtrainerActionPerformed

    private void phonetrainer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonetrainer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonetrainer1ActionPerformed

    private void specialtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_specialtyActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        login r = new login();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bio;
    private javax.swing.JTextField emailtrainer;
    private javax.swing.JTextField fullnametrainer;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField passtrainer;
    private javax.swing.JTextField phonetrainer1;
    private javax.swing.JTextField specialty;
    // End of variables declaration//GEN-END:variables
}
