/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trainermenu;

import adminmenu.add1;
import config.config;
import config.UserSession;

/**
 *
 * @author Lloyd's PC
 */
public class addclass extends javax.swing.JFrame {

    public int trainer_id; // Set this when you open the frame
    /**
     * Creates new form addclass
     */
    public addclass() {
    // SECURITY CHECK: Redirect if not logged in
    if (UserSession.getInstance().getFullName() == null) {
        javax.swing.JOptionPane.showMessageDialog(null, "No active session. Redirecting to Login...");
        new main.landing().setVisible(true);
        this.dispose();
        return; 
    }
    
    initComponents();
    
    // Automatically set the trainer_id from the session so you don't have to do it manually!
    this.trainer_id = UserSession.getInstance().getId();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        maxcapacity = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        classsched = new javax.swing.JTextField();
        ADDCLASSBOT = new javax.swing.JLabel();
        classname1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(39, 41, 46));
        jPanel1.setPreferredSize(new java.awt.Dimension(910, 610));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(51, 51, 51));
        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 3, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(170, 231, 37));
        jLabel12.setText("1. Class name:");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        maxcapacity.setBackground(new java.awt.Color(39, 41, 46));
        maxcapacity.setForeground(new java.awt.Color(255, 255, 255));
        maxcapacity.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        maxcapacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxcapacityActionPerformed(evt);
            }
        });
        jPanel1.add(maxcapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 340, 40));

        jLabel13.setBackground(new java.awt.Color(51, 51, 51));
        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 3, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(170, 231, 37));
        jLabel13.setText("2. Class Schedule: ");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jLabel14.setBackground(new java.awt.Color(51, 51, 51));
        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 3, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(170, 231, 37));
        jLabel14.setText("3. Max Capacity:");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        classsched.setBackground(new java.awt.Color(39, 41, 46));
        classsched.setForeground(new java.awt.Color(255, 255, 255));
        classsched.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        classsched.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classschedActionPerformed(evt);
            }
        });
        jPanel1.add(classsched, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 330, 40));

        ADDCLASSBOT.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        ADDCLASSBOT.setForeground(new java.awt.Color(255, 255, 255));
        ADDCLASSBOT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus1.png"))); // NOI18N
        ADDCLASSBOT.setText("ADD CLASS");
        ADDCLASSBOT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADDCLASSBOTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ADDCLASSBOTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ADDCLASSBOTMouseExited(evt);
            }
        });
        jPanel1.add(ADDCLASSBOT, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, -1, -1));

        classname1.setBackground(new java.awt.Color(39, 41, 46));
        classname1.setForeground(new java.awt.Color(255, 255, 255));
        classname1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        classname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classname1ActionPerformed(evt);
            }
        });
        jPanel1.add(classname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 330, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseExited

    private void maxcapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxcapacityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxcapacityActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseExited

    private void classschedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classschedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classschedActionPerformed

    private void ADDCLASSBOTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDCLASSBOTMouseClicked
   config con = new config();
    
    String name = classname1.getText();
    String sched = classsched.getText();
    String capStr = maxcapacity.getText();
    
    if (name.isEmpty() || sched.isEmpty() || capStr.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(null, "All fields are required!");
        return;
    }

    try {
        int capacity = Integer.parseInt(capStr);
        String sql = "INSERT INTO tbl_classes (t_id, class_name, schedule, max_capacity) VALUES (?, ?, ?, ?)";
        
        con.addRecord(sql, trainer_id, name, sched, capacity);
        
        javax.swing.JOptionPane.showMessageDialog(null, "Class Added Successfully!");
        
        // CLEAR FIELDS FOR NEXT ENTRY
        classname1.setText("");
        classsched.setText("");
        maxcapacity.setText("");
        
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Max Capacity must be a number!");
    }
    }//GEN-LAST:event_ADDCLASSBOTMouseClicked

    private void ADDCLASSBOTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDCLASSBOTMouseEntered
        ADDCLASSBOT.setForeground(new java.awt.Color(170, 231, 37));
    }//GEN-LAST:event_ADDCLASSBOTMouseEntered

    private void ADDCLASSBOTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDCLASSBOTMouseExited
        ADDCLASSBOT.setForeground(new java.awt.Color(255, 255, 255)); // White
    }//GEN-LAST:event_ADDCLASSBOTMouseExited

    private void classname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classname1ActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        ex.printStackTrace();
    }

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            // LOCK THE PREVIEW
            if (UserSession.getInstance().getFullName() == null) {
                javax.swing.JOptionPane.showMessageDialog(null, "Please log in first!");
                new main.landing().setVisible(true);
                return; // Stop the window from being created
            }
            
            new addclass().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ADDCLASSBOT;
    private javax.swing.JTextField classname1;
    private javax.swing.JTextField classsched;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField maxcapacity;
    // End of variables declaration//GEN-END:variables
}
