/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminmenu;

/**
 *
 * @author Lloyd's PC
 */
public class addclass extends javax.swing.JPanel {

    /**
     * Creates new form addclass
     */
    public addclass() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        adminclassname1 = new javax.swing.JTextField();
        adminclasssched = new javax.swing.JTextField();
        trainerid = new javax.swing.JTextField();
        adminmaxcapacity1 = new javax.swing.JTextField();
        adminADDCLASS = new javax.swing.JLabel();

        jInternalFrame1.setPreferredSize(new java.awt.Dimension(718, 514));
        jInternalFrame1.setVisible(true);

        jPanel2.setBackground(new java.awt.Color(39, 41, 46));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(51, 51, 51));
        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(170, 231, 37));
        jLabel14.setText("4. Trainer Id:");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel12.setBackground(new java.awt.Color(51, 51, 51));
        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(170, 231, 37));
        jLabel12.setText("1. Class name:");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel13.setBackground(new java.awt.Color(51, 51, 51));
        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(170, 231, 37));
        jLabel13.setText("2. Class Schedule: ");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel15.setBackground(new java.awt.Color(51, 51, 51));
        jLabel15.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(170, 231, 37));
        jLabel15.setText("3. Max Capacity:");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel15MouseExited(evt);
            }
        });
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        adminclassname1.setBackground(new java.awt.Color(39, 41, 46));
        adminclassname1.setForeground(new java.awt.Color(255, 255, 255));
        adminclassname1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        adminclassname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminclassname1ActionPerformed(evt);
            }
        });
        jPanel2.add(adminclassname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 340, 40));

        adminclasssched.setBackground(new java.awt.Color(39, 41, 46));
        adminclasssched.setForeground(new java.awt.Color(255, 255, 255));
        adminclasssched.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        adminclasssched.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminclassschedActionPerformed(evt);
            }
        });
        jPanel2.add(adminclasssched, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 340, 40));

        trainerid.setBackground(new java.awt.Color(39, 41, 46));
        trainerid.setForeground(new java.awt.Color(255, 255, 255));
        trainerid.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        trainerid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traineridActionPerformed(evt);
            }
        });
        jPanel2.add(trainerid, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 340, 40));

        adminmaxcapacity1.setBackground(new java.awt.Color(39, 41, 46));
        adminmaxcapacity1.setForeground(new java.awt.Color(255, 255, 255));
        adminmaxcapacity1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        adminmaxcapacity1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminmaxcapacity1ActionPerformed(evt);
            }
        });
        jPanel2.add(adminmaxcapacity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 340, 40));

        adminADDCLASS.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        adminADDCLASS.setForeground(new java.awt.Color(255, 255, 255));
        adminADDCLASS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus1.png"))); // NOI18N
        adminADDCLASS.setText("ADD CLASS");
        adminADDCLASS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminADDCLASSMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminADDCLASSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminADDCLASSMouseExited(evt);
            }
        });
        jPanel2.add(adminADDCLASS, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, -1));

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void adminclassschedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminclassschedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminclassschedActionPerformed

    private void adminmaxcapacity1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminmaxcapacity1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminmaxcapacity1ActionPerformed

    private void traineridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traineridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_traineridActionPerformed

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseExited

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseExited

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseEntered

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseExited

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    private void adminclassname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminclassname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminclassname1ActionPerformed

    private void adminADDCLASSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminADDCLASSMouseClicked
   // 1. Initialize DB Config
        config.config con = new config.config();

        // 2. Get data from your text fields
        String className = adminclassname1.getText().trim();
        String schedule = adminclasssched.getText().trim();
        String maxCapRaw = adminmaxcapacity1.getText().trim();
        String trainerIdRaw = trainerid.getText().trim();

        // 3. Validation: Check if fields are empty
        if (className.isEmpty() || schedule.isEmpty() || maxCapRaw.isEmpty() || trainerIdRaw.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Error: All fields are required!");
            return;
        }

        try {
            // Convert numbers
            int capacity = Integer.parseInt(maxCapRaw);
            int t_id = Integer.parseInt(trainerIdRaw);

            // 4. CHECK IF TRAINER EXISTS in tbl_trainers
            // This ensures the ID entered belongs to a real trainer
            String checkTrainerSql = "SELECT COUNT(*) FROM tbl_trainers WHERE t_id = " + t_id;
            
            // Using a standard check: if count is 0, trainer doesn't exist
            if (con.getScalar(checkTrainerSql) == 0) {
                javax.swing.JOptionPane.showMessageDialog(null, "Error: Trainer ID [" + t_id + "] does not exist!\n"
                        + "Please verify the ID in the Trainer list.");
                return; // Stop here and don't save
            }

            // 5. IF TRAINER EXISTS, PROCEED TO INSERT INTO tbl_classes
            String insertSql = "INSERT INTO tbl_classes (t_id, class_name, schedule, max_capacity) VALUES (?, ?, ?, ?)";
            
            con.addRecord(insertSql, t_id, className, schedule, capacity);

            // 6. Success Message and Clear Fields
            javax.swing.JOptionPane.showMessageDialog(null, "SUCCESS: Class '" + className + "' has been added!");
            
            adminclassname1.setText("");
            adminclasssched.setText("");
            adminmaxcapacity1.setText("");
            trainerid.setText("");

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Error: Max Capacity and Trainer ID must be valid numbers!");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Database Error: " + e.getMessage());
        }
    }//GEN-LAST:event_adminADDCLASSMouseClicked

    private void adminADDCLASSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminADDCLASSMouseEntered
        adminADDCLASS.setForeground(new java.awt.Color(170, 231, 37));
    }//GEN-LAST:event_adminADDCLASSMouseEntered

    private void adminADDCLASSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminADDCLASSMouseExited
        adminADDCLASS.setForeground(new java.awt.Color(255, 255, 255)); // White
    }//GEN-LAST:event_adminADDCLASSMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminADDCLASS;
    private javax.swing.JTextField adminclassname1;
    private javax.swing.JTextField adminclasssched;
    private javax.swing.JTextField adminmaxcapacity1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField trainerid;
    // End of variables declaration//GEN-END:variables
}
