/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminmenu;

/**
 *
 * @author Lloyd's PC
 */
public class edit extends javax.swing.JPanel {

    /**
     * Creates new form edit
     */
    // Inside edit.java
public edit(String id, String name, String email, String phone, String type, String status) {
    initComponents();
    this.fullname.setText(id);
    this.fullname1.setText(name);
    this.email1.setText(email);
    this.phonenum1.setText(phone);
    this.usertype.setText(type);   // Set the Type here
    this.userstat2.setText(status); // Set the Status here
    
    this.fullname.setEditable(false);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fullname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        edituser = new javax.swing.JLabel();
        usertype = new javax.swing.JTextField();
        phonenum1 = new javax.swing.JTextField();
        email1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fullname1 = new javax.swing.JTextField();
        userstat2 = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(39, 41, 46));
        jPanel1.setPreferredSize(new java.awt.Dimension(718, 514));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fullname.setBackground(new java.awt.Color(39, 41, 46));
        fullname.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        fullname.setForeground(new java.awt.Color(255, 255, 255));
        fullname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fullname.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "id", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 2, 14), new java.awt.Color(102, 255, 102))); // NOI18N
        fullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameActionPerformed(evt);
            }
        });
        jPanel1.add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 270, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loGo12.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 170, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        edituser.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        edituser.setForeground(new java.awt.Color(255, 255, 255));
        edituser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edits.png"))); // NOI18N
        edituser.setText("Edit User");
        edituser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edituserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                edituserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                edituserMouseExited(evt);
            }
        });
        jPanel1.add(edituser, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        usertype.setBackground(new java.awt.Color(39, 41, 46));
        usertype.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        usertype.setForeground(new java.awt.Color(255, 255, 255));
        usertype.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "usertype", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 2, 14), new java.awt.Color(102, 255, 102))); // NOI18N
        usertype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usertypeActionPerformed(evt);
            }
        });
        jPanel1.add(usertype, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 270, 80));

        phonenum1.setBackground(new java.awt.Color(39, 41, 46));
        phonenum1.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        phonenum1.setForeground(new java.awt.Color(255, 255, 255));
        phonenum1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "phonenum", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 2, 14), new java.awt.Color(102, 255, 102))); // NOI18N
        phonenum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenum1ActionPerformed(evt);
            }
        });
        jPanel1.add(phonenum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 270, 80));

        email1.setBackground(new java.awt.Color(39, 41, 46));
        email1.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        email1.setForeground(new java.awt.Color(255, 255, 255));
        email1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "email", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 2, 14), new java.awt.Color(102, 255, 102))); // NOI18N
        email1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email1ActionPerformed(evt);
            }
        });
        jPanel1.add(email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 270, 80));

        jLabel14.setBackground(new java.awt.Color(51, 51, 51));
        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(170, 231, 37));
        jLabel14.setText("User's Info");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jLabel12.setBackground(new java.awt.Color(51, 51, 51));
        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(170, 231, 37));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        fullname1.setBackground(new java.awt.Color(39, 41, 46));
        fullname1.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        fullname1.setForeground(new java.awt.Color(255, 255, 255));
        fullname1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "fullname", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 2, 14), new java.awt.Color(102, 255, 102))); // NOI18N
        fullname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullname1ActionPerformed(evt);
            }
        });
        jPanel1.add(fullname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 270, 80));

        userstat2.setBackground(new java.awt.Color(39, 41, 46));
        userstat2.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        userstat2.setForeground(new java.awt.Color(255, 255, 255));
        userstat2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "userstatus", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 2, 14), new java.awt.Color(102, 255, 102))); // NOI18N
        userstat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userstat2ActionPerformed(evt);
            }
        });
        jPanel1.add(userstat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 270, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameActionPerformed

    private void edituserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edituserMouseClicked
config.config conf = new config.config();
    
    // 1. Get values from your text fields
    String id = fullname.getText();
    String name = fullname1.getText();
    String email = email1.getText();
    String phone = phonenum1.getText();
    String status = userstat2.getText(); 
    
    // 2. Capture and Clean the Type
    String inputType = usertype.getText().trim();
    String type = "Unassigned"; 

    if (inputType.equalsIgnoreCase("admin")) {
        type = "Admin";
    } else if (inputType.equalsIgnoreCase("staff")) {
        type = "Staff";
    } else if (inputType.equalsIgnoreCase("member")) {
        type = "Member";
    } else if (inputType.equalsIgnoreCase("trainer")) {
        type = "Trainer";
    }

    // 3. Validation
    if (id.isEmpty() || name.isEmpty() || email.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(null, "Required fields are empty!");
        return;
    }

    // 4. Update the main users table
    String sqlUpdate = "UPDATE users_tbl SET full_name = ?, email = ?, phonenumber = ?, u_type = ?, U_status = ? WHERE u_id = ?";
    
    try {
        conf.addRecord(sqlUpdate, name, email, phone, type, status, id);

        // 5. THE BRIDGE: Create specialized records if they don't exist
        if (type.equals("Member")) {
            // Links u_id to m_id
            String memberSql = "INSERT OR IGNORE INTO tbl_members (m_id, m_fname, m_email, m_phonenumber, join_date) VALUES (?, ?, ?, ?, DATE('now'))";
            conf.addRecord(memberSql, id, name, email, phone);
        } 
        else if (type.equals("Trainer")) {
            // CRITICAL: This creates the row in tbl_trainers so a t_id is generated
            // specialty and bio are set to defaults
            String trainerSql = "INSERT OR IGNORE INTO tbl_trainers (u_id, specialty, bio) VALUES (?, 'No specialty yet', 'No bio yet')";
            conf.addRecord(trainerSql, id);
        }

        javax.swing.JOptionPane.showMessageDialog(null, "Update Successful! User " + name + " is now a " + type);
        
        // 6. Refresh Table and Return
        ViewUsers vu = new ViewUsers();
        javax.swing.JComponent container = (javax.swing.JComponent) this.getParent();
        container.removeAll();
        vu.setSize(container.getWidth(), container.getHeight());
        container.add(vu);
        container.revalidate();
        container.repaint();
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Database Error: " + e.getMessage());
    }
    }//GEN-LAST:event_edituserMouseClicked

    private void edituserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edituserMouseEntered
        edituser.setForeground(new java.awt.Color(170, 231, 37));
    }//GEN-LAST:event_edituserMouseEntered

    private void edituserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edituserMouseExited
        edituser.setForeground(new java.awt.Color(255, 255, 255)); // White
    }//GEN-LAST:event_edituserMouseExited

    private void usertypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usertypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usertypeActionPerformed

    private void phonenum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonenum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonenum1ActionPerformed

    private void email1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email1ActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseExited

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseExited

    private void fullname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullname1ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        ViewUsers vu = new ViewUsers();
    javax.swing.JComponent container = (javax.swing.JComponent) this.getParent();
    container.removeAll();
    vu.setSize(container.getWidth(), container.getHeight());
    container.add(vu);
    container.revalidate();
    container.repaint();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void userstat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userstat2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userstat2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel edituser;
    public javax.swing.JTextField email1;
    public javax.swing.JTextField fullname;
    public javax.swing.JTextField fullname1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField phonenum1;
    public javax.swing.JTextField userstat2;
    public javax.swing.JTextField usertype;
    // End of variables declaration//GEN-END:variables
}
