/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminmenu;

import adminmenu.profile;
import config.config;

public class profile extends javax.swing.JInternalFrame {

    /**
     * Creates new form profile
     */
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        adminname = new javax.swing.JLabel();
        ad = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        adminphonenumber = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        adminemail1 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jPanel4.setBackground(new java.awt.Color(39, 41, 46));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(170, 231, 37));
        jLabel3.setText("User Info");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(170, 231, 37));
        jLabel4.setText("Phone number:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 300, 45));

        adminname.setBackground(new java.awt.Color(187, 187, 187));
        adminname.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        adminname.setForeground(new java.awt.Color(170, 231, 37));
        adminname.setText("jLabel2");
        adminname.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                adminnameInputMethodTextChanged(evt);
            }
        });
        jPanel4.add(adminname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        ad.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        ad.setForeground(new java.awt.Color(170, 231, 37));
        ad.setText("User type: Admin");
        ad.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                adInputMethodTextChanged(evt);
            }
        });
        jPanel4.add(ad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(170, 231, 37));
        jLabel6.setText("Full name:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 210, 45));

        adminphonenumber.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        adminphonenumber.setForeground(new java.awt.Color(170, 231, 37));
        adminphonenumber.setText("#######");
        jPanel4.add(adminphonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 190, 45));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(170, 231, 37));
        jLabel8.setText("User Email:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 250, 45));

        adminemail1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        adminemail1.setForeground(new java.awt.Color(170, 231, 37));
        adminemail1.setText("Email");
        jPanel4.add(adminemail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 130, 45));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminnameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_adminnameInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_adminnameInputMethodTextChanged

    private void adInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_adInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_adInputMethodTextChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ad;
    private javax.swing.JLabel adminemail1;
    private javax.swing.JLabel adminname;
    private javax.swing.JLabel adminphonenumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
