/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminmenu;

import config.config;

/**
 *
 * @author Lloyd's PC
 */
public class ViewUsers extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewUser
     */
    public ViewUsers() {
        initComponents();
        displayUser();
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        // Put this in the ViewUsers() constructor as well
this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0)); // Removes the frame border
((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null); // Optional: Removes the title bar entirely
        // 1. Make the Table and ScrollPane transparent
    userst.setOpaque(false);
    jScrollPane1.setOpaque(false);
    jScrollPane1.getViewport().setOpaque(false);
    

    // 2. Make the cells transparent so the background shows through
    ((javax.swing.table.DefaultTableCellRenderer)userst.getDefaultRenderer(Object.class)).setOpaque(false);

    // 3. Set the background color to match YOUR panel's specific grey (39, 41, 46)
    userst.setBackground(new java.awt.Color(39, 41, 46));
    // 1. Style the Header (the top part with column names)
userst.getTableHeader().setBackground(new java.awt.Color(39, 41, 46)); // Matches your panel
userst.getTableHeader().setForeground(new java.awt.Color(170, 231, 37)); // Matches your neon text
userst.getTableHeader().setFont(new java.awt.Font("Segoe UI Black", 1, 14));
userst.getTableHeader().setOpaque(false);
userst.getTableHeader().setBorder(null);
jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder());

// 2. Remove the default border that causes the "boxy" look
userst.getTableHeader().setBorder(null);

// 3. To make it truly seamless, remove the ScrollPane border too
jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    
    // 4. Bonus: Hide the border of the scroll pane for a cleaner look
    jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    // Force the header to stop using the default "Blue" theme style
userst.getTableHeader().setDefaultRenderer(new javax.swing.table.DefaultTableCellRenderer() {
    @Override
    public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
        setBackground(new java.awt.Color(39, 41, 46)); // Matches your panel grey
        setForeground(new java.awt.Color(170, 231, 37)); // Your neon green text
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 60, 60))); // Subtle border
        setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        return this;
    }
});
    }
    void displayUser()
    {
        config con = new config();
        String sql = "SELECT * FROM users_tbl";
        con.displayData(sql, userst);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userst = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(39, 41, 46));
        jPanel1.setPreferredSize(new java.awt.Dimension(686, 370));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userst.setBackground(new java.awt.Color(39, 41, 46));
        userst.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        userst.setForeground(new java.awt.Color(170, 231, 37));
        userst.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        userst.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        userst.setGridColor(new java.awt.Color(153, 153, 153));
        userst.setPreferredSize(new java.awt.Dimension(686, 370));
        userst.setSelectionBackground(new java.awt.Color(204, 204, 204));
        userst.setSelectionForeground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(userst);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 690, 380));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(170, 231, 37));
        jLabel1.setText("USERS TABLE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable userst;
    // End of variables declaration//GEN-END:variables
}
