/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admindash;



import adminmenu.*;



/**
 *
 * @author Lloyd's PC
 */
public class admindashboard extends javax.swing.JFrame {


public admindashboard(String name) {
    initComponents();
    menu.setBackground(new java.awt.Color(39, 41, 46));
    menu.setOpaque(true);
    
    // 2. Fetch the session and display it
    displayUserInfo();
    
}
private void displayUserInfo() {
    config.UserSession sess = config.UserSession.getInstance();
    
    if (sess.getFname() != null) {
        namead.setText("Name: " + sess.getFname() + " " + sess.getLname());
        phonead.setText("Phone: " + sess.getContact());
        gmailad.setText("Email: " + sess.getEmail());
        usertypead.setText("UserType: " + sess.getType());
    } else {
        namead.setText("Name: ");
    }
}

    public admindashboard() {
initComponents();
    displayUserInfo();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        userst = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        adminname = new javax.swing.JLabel();
        ad = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        adminphonenumber = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        adminemail1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        viewUsers = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        menu = new javax.swing.JDesktopPane();
        gmailad = new javax.swing.JLabel();
        phonead = new javax.swing.JLabel();
        namead = new javax.swing.JLabel();
        usertypead = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        userst.setBackground(new java.awt.Color(0, 0, 0));
        userst.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        userst.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        userst.setForeground(new java.awt.Color(255, 255, 255));
        userst.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        userst.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        userst.setGridColor(new java.awt.Color(255, 255, 255));
        userst.setSelectionBackground(new java.awt.Color(204, 204, 204));
        userst.setSelectionForeground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(userst);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("User Info");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 132, -1, -1));

        jLabel4.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Phone number:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 160, 45));

        adminname.setBackground(new java.awt.Color(187, 187, 187));
        adminname.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        adminname.setForeground(new java.awt.Color(51, 51, 51));
        adminname.setText("jLabel2");
        adminname.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                adminnameInputMethodTextChanged(evt);
            }
        });
        jPanel4.add(adminname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        ad.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        ad.setForeground(new java.awt.Color(51, 51, 51));
        ad.setText("User type: Admin");
        ad.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                adInputMethodTextChanged(evt);
            }
        });
        jPanel4.add(ad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Full name:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 119, 45));

        adminphonenumber.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        adminphonenumber.setForeground(new java.awt.Color(51, 51, 51));
        adminphonenumber.setText("#######");
        jPanel4.add(adminphonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 130, 45));

        jLabel8.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("User Email:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 130, 45));

        adminemail1.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        adminemail1.setForeground(new java.awt.Color(51, 51, 51));
        adminemail1.setText("Email");
        jPanel4.add(adminemail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 130, 45));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(39, 41, 46));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(170, 231, 37), 3, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewUsers.setBackground(new java.awt.Color(170, 231, 37));
        viewUsers.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        viewUsers.setForeground(new java.awt.Color(0, 0, 0));
        viewUsers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewUsers.setText("View Users");
        viewUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewUsersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewUsersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewUsersMouseExited(evt);
            }
        });
        jPanel2.add(viewUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 180, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/viewad.png"))); // NOI18N
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/managead.png"))); // NOI18N
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Manage Trainers");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/managetrain.png"))); // NOI18N
        jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Manage Members");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 610));

        jPanel6.setBackground(new java.awt.Color(39, 41, 46));

        menu.setBackground(new java.awt.Color(39, 41, 46));

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 686, Short.MAX_VALUE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(menu)
                .addGap(25, 25, 25))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(menu)
                .addContainerGap())
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 730, 520));

        gmailad.setBackground(new java.awt.Color(170, 231, 37));
        gmailad.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        gmailad.setForeground(new java.awt.Color(170, 231, 37));
        gmailad.setText("gmail:");
        jPanel1.add(gmailad, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, -1));

        phonead.setBackground(new java.awt.Color(170, 231, 37));
        phonead.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        phonead.setForeground(new java.awt.Color(170, 231, 37));
        phonead.setText("Phone:");
        jPanel1.add(phonead, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        namead.setBackground(new java.awt.Color(170, 231, 37));
        namead.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        namead.setForeground(new java.awt.Color(170, 231, 37));
        namead.setText("Name:");
        jPanel1.add(namead, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        usertypead.setBackground(new java.awt.Color(170, 231, 37));
        usertypead.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        usertypead.setForeground(new java.awt.Color(170, 231, 37));
        usertypead.setText("UserType:");
        jPanel1.add(usertypead, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_adInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_adInputMethodTextChanged

    private void adminnameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_adminnameInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_adminnameInputMethodTextChanged

    private void viewUsersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewUsersMouseExited
        viewUsers.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_viewUsersMouseExited

    private void viewUsersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewUsersMouseEntered
        viewUsers.setForeground(new java.awt.Color(102,102,102));
    }//GEN-LAST:event_viewUsersMouseEntered

    private void viewUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewUsersMouseClicked
      ViewUsers up = new ViewUsers();
        menu.add(up).setVisible(true);
    }//GEN-LAST:event_viewUsersMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
      ViewUsers up = new ViewUsers();
        menu.add(up).setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

   
    
 public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            // This just opens the window
            new admindashboard("Admin").setVisible(true); 
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ad;
    private javax.swing.JLabel adminemail1;
    private javax.swing.JLabel adminname;
    private javax.swing.JLabel adminphonenumber;
    private javax.swing.JLabel gmailad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDesktopPane menu;
    private javax.swing.JLabel namead;
    private javax.swing.JLabel phonead;
    private javax.swing.JTable userst;
    private javax.swing.JLabel usertypead;
    private javax.swing.JLabel viewUsers;
    // End of variables declaration//GEN-END:variables
}
