/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DASHBOARDS;



import adminmenu.*;
import config.UserSession;
import main.landing;



/**
 *
 * @author Lloyd's PC
 */
public class admindashboard extends javax.swing.JFrame {



private void displayUserInfo() {
    config.UserSession sess = config.UserSession.getInstance();
    
    // Check if fullName is set to determine if logged in
    if (sess.getFullName() != null) {
    namead.setText("Name: " + sess.getFullName()); // Uses full_name from DB
    gmailad.setText("Email: " + sess.getEmail());
    usertypead.setText("UserType: " + sess.getType());
} else {
    namead.setText("Name: Guest");
}
}
  public admindashboard() {
    // --- SECURITY CHECK START ---
    if (config.UserSession.getInstance().getFullName() == null) {
        javax.swing.JOptionPane.showMessageDialog(null, "Access Denied: Please log in first!");
        new main.landing().setVisible(true);
        this.dispose();
        return; 
    }
    // --- SECURITY CHECK END ---

    initComponents();
    
    // Set UI styling
    if (menu != null) {
        menu.setBackground(new java.awt.Color(39, 41, 46));
        menu.setOpaque(true);
    }
    
    // Fetch and display user data
    displayUserInfo();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        userst = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        adminname = new javax.swing.JLabel();
        ad = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        adminphonenumber = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        adminemail1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        viewUsers = new javax.swing.JLabel();
        manageusers = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        createclass = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        menu = new javax.swing.JDesktopPane();
        gmailad = new javax.swing.JLabel();
        namead = new javax.swing.JLabel();
        usertypead = new javax.swing.JLabel();
        editprofileadmin = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();

        userst.setBackground(new java.awt.Color(0, 0, 0));
        userst.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        userst.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        userst.setForeground(new java.awt.Color(255, 255, 255));
        userst.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        userst.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        userst.setGridColor(new java.awt.Color(255, 255, 255));
        userst.setSelectionBackground(new java.awt.Color(204, 204, 204));
        userst.setSelectionForeground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(userst);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("User Info");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 132, -1, -1));

        jLabel4.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Phone number:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 160, 45));

        adminname.setBackground(new java.awt.Color(187, 187, 187));
        adminname.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        adminname.setForeground(new java.awt.Color(51, 51, 51));
        adminname.setText("jLabel2");
        adminname.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                adminnameInputMethodTextChanged(evt);
            }
        });
        jPanel4.add(adminname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        ad.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        ad.setForeground(new java.awt.Color(51, 51, 51));
        ad.setText("User type: Admin");
        ad.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                adInputMethodTextChanged(evt);
            }
        });
        jPanel4.add(ad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Full name:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 119, 45));

        adminphonenumber.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        adminphonenumber.setForeground(new java.awt.Color(51, 51, 51));
        adminphonenumber.setText("#######");
        jPanel4.add(adminphonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 130, 45));

        jLabel8.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("User Email:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 130, 45));

        adminemail1.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        adminemail1.setForeground(new java.awt.Color(51, 51, 51));
        adminemail1.setText("Email");
        jPanel4.add(adminemail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 130, 45));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(39, 41, 46));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(170, 231, 37), 3, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewUsers.setBackground(new java.awt.Color(170, 231, 37));
        viewUsers.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        viewUsers.setForeground(new java.awt.Color(0, 0, 0));
        viewUsers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewUsers.setText("Manage Users");
        viewUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewUsersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewUsersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewUsersMouseExited(evt);
            }
        });
        jPanel2.add(viewUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 30));

        manageusers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/viewad1.png"))); // NOI18N
        manageusers.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        manageusers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageusersMouseClicked(evt);
            }
        });
        jPanel2.add(manageusers, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 100, 100));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/managead1.png"))); // NOI18N
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        createclass.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        createclass.setForeground(new java.awt.Color(0, 0, 0));
        createclass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/create.png"))); // NOI18N
        createclass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        createclass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createclassMouseClicked(evt);
            }
        });
        jPanel2.add(createclass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/managetrain1.png"))); // NOI18N
        jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Manage Members");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Manage Trainers");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Create a Class");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 610));

        jPanel6.setBackground(new java.awt.Color(39, 41, 46));

        menu.setBackground(new java.awt.Color(39, 41, 46));

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(menu)
                .addContainerGap())
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 730, 520));

        gmailad.setBackground(new java.awt.Color(170, 231, 37));
        gmailad.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        gmailad.setForeground(new java.awt.Color(170, 231, 37));
        gmailad.setText("gmail:");
        jPanel1.add(gmailad, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 210, -1));

        namead.setBackground(new java.awt.Color(170, 231, 37));
        namead.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        namead.setForeground(new java.awt.Color(170, 231, 37));
        namead.setText("Name:");
        jPanel1.add(namead, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 160, -1));

        usertypead.setBackground(new java.awt.Color(170, 231, 37));
        usertypead.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        usertypead.setForeground(new java.awt.Color(170, 231, 37));
        usertypead.setText("UserType:");
        jPanel1.add(usertypead, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 480, -1));

        editprofileadmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile1.png"))); // NOI18N
        editprofileadmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editprofileadminMouseClicked(evt);
            }
        });
        jPanel1.add(editprofileadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        logout.setBackground(new java.awt.Color(51, 51, 51));
        logout.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(170, 231, 37));
        logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout.setText("Log out");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_adInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_adInputMethodTextChanged

    private void adminnameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_adminnameInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_adminnameInputMethodTextChanged

    private void viewUsersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewUsersMouseExited
        viewUsers.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_viewUsersMouseExited

    private void viewUsersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewUsersMouseEntered
        viewUsers.setForeground(new java.awt.Color(102,102,102));
    }//GEN-LAST:event_viewUsersMouseEntered

    private void viewUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewUsersMouseClicked
      ViewUsers up = new ViewUsers();
        menu.add(up).setVisible(true);
    }//GEN-LAST:event_viewUsersMouseClicked

    private void manageusersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageusersMouseClicked
      ViewUsers up = new ViewUsers();
        menu.add(up).setVisible(true);
    }//GEN-LAST:event_manageusersMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // 1. (Optional) Clear the user session if you want to be secure
        UserSession.getInstance().setFullName(null);
        UserSession.getInstance().setEmail(null);
        UserSession.getInstance().setType(null);

        // 2. Open the landing page
        // Replace 'landingpage' with the actual name of your landing page class
        landing land = new landing();
        land.setVisible(true);

        // 3. Close the current dashboard
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        // TODO add your handling code here:
        logout.setForeground(java.awt.Color.RED);
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        // TODO add your handling code here:
        logout.setForeground(new java.awt.Color(170, 231, 37));
    }//GEN-LAST:event_logoutMouseExited

    private void createclassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createclassMouseClicked
    // 1. Create the instance of your panel
    adminmenu.addclass up = new adminmenu.addclass();
    
    // 2. Clear the desktop (the 'menu' variable) so screens don't stack
    menu.removeAll();
    
    // 3. Add the panel to the JDesktopPane
    menu.add(up);
    
    // 4. Center the content and make sure it fills the area
    up.setSize(menu.getWidth(), menu.getHeight());
    up.setVisible(true);
    
    // 5. Refresh the UI so the new page appears immediately
    menu.revalidate();
    menu.repaint();
    }//GEN-LAST:event_createclassMouseClicked

    private void editprofileadminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editprofileadminMouseClicked
// 1. Create the instance
    memberDASHBOARD.editprofile up = new memberDASHBOARD.editprofile();
    
    // 2. Clear the desktop pane (menu)
    menu.removeAll();
    
    // 3. Add the panel to the menu
    menu.add(up);
    
    // 4. Set size to match the menu area
    up.setSize(menu.getWidth(), menu.getHeight());
    up.setLocation(0, 0); // Ensure it starts at the top-left
    up.setVisible(true);
    
    // 5. Refresh everything
    menu.revalidate();
    menu.repaint();      // TODO add your handling code here:
    }//GEN-LAST:event_editprofileadminMouseClicked

   
    
public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            // Check if session exists before showing the dashboard
            if (config.UserSession.getInstance().getFullName() == null) {
                javax.swing.JOptionPane.showMessageDialog(null, "Security Alert: Login required.");
                new main.landing().setVisible(true);
            } else {
                new admindashboard().setVisible(true);
            }
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ad;
    private javax.swing.JLabel adminemail1;
    private javax.swing.JLabel adminname;
    private javax.swing.JLabel adminphonenumber;
    private javax.swing.JLabel createclass;
    private javax.swing.JLabel editprofileadmin;
    private javax.swing.JLabel gmailad;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel manageusers;
    private javax.swing.JDesktopPane menu;
    private javax.swing.JLabel namead;
    private javax.swing.JTable userst;
    private javax.swing.JLabel usertypead;
    private javax.swing.JLabel viewUsers;
    // End of variables declaration//GEN-END:variables
}
