/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import internalPages.Adminpage;
import java.awt.Color;
import internalPages.Memberpage;
import internalPages.Trainerpage;

public class register extends javax.swing.JFrame {

 
    public register() {
        initComponents();
        desktopInstance.setBackground(new java.awt.Color(50, 50, 50)); // Your choice of color
desktopInstance.setOpaque(true);
    }
    Color navcolor = new Color(51,51,51);
    Color headcolor = new Color(51,0,0);
    Color bodycolor = new Color(204,204,204);
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        trainer = new javax.swing.JLabel();
        admins = new javax.swing.JLabel();
        members = new javax.swing.JLabel();
        desktopInstance = new javax.swing.JDesktopPane() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                // Use the RGB values from your sidebar to make it match
                g.setColor(new java.awt.Color(39,41,46)); 
                g.fillRect(0, 0, getWidth(), getHeight());
            }
        };

        jTextField4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        body.setBackground(new java.awt.Color(204, 204, 204));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(39, 41, 46));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        trainer.setFont(new java.awt.Font("Segoe UI Black", 3, 36)); // NOI18N
        trainer.setForeground(new java.awt.Color(170, 231, 37));
        trainer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        trainer.setText("Trainer");
        trainer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trainerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                trainerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                trainerMouseExited(evt);
            }
        });
        header.add(trainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 170, -1));

        admins.setFont(new java.awt.Font("Segoe UI Black", 3, 36)); // NOI18N
        admins.setForeground(new java.awt.Color(170, 231, 37));
        admins.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        admins.setText("Admin");
        admins.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminsMouseExited(evt);
            }
        });
        header.add(admins, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 170, -1));

        members.setBackground(new java.awt.Color(51, 51, 51));
        members.setFont(new java.awt.Font("Segoe UI Black", 3, 36)); // NOI18N
        members.setForeground(new java.awt.Color(170, 231, 37));
        members.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        members.setText("Member");
        members.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                membersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                membersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                membersMouseExited(evt);
            }
        });
        header.add(members, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 170, -1));

        body.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 90));

        desktopInstance.setBackground(new java.awt.Color(39, 41, 46));

        javax.swing.GroupLayout desktopInstanceLayout = new javax.swing.GroupLayout(desktopInstance);
        desktopInstance.setLayout(desktopInstanceLayout);
        desktopInstanceLayout.setHorizontalGroup(
            desktopInstanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        desktopInstanceLayout.setVerticalGroup(
            desktopInstanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        body.add(desktopInstance, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void trainerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trainerMouseEntered
       trainer.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_trainerMouseEntered

    private void trainerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trainerMouseExited
        trainer.setForeground(new java.awt.Color(170,231,37));
    }//GEN-LAST:event_trainerMouseExited

    private void trainerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trainerMouseClicked
      Trainerpage up = new Trainerpage();
        desktopInstance.add(up).setVisible(true);
    }//GEN-LAST:event_trainerMouseClicked

    private void adminsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminsMouseExited
        admins.setForeground(new java.awt.Color(170,231,37));
    }//GEN-LAST:event_adminsMouseExited

    private void adminsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminsMouseEntered
        admins.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_adminsMouseEntered

    private void adminsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminsMouseClicked
        desktopInstance.removeAll();
        Adminpage admin = new Adminpage();
        desktopInstance.add(admin).setVisible(true);
    }//GEN-LAST:event_adminsMouseClicked

    private void membersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_membersMouseExited
        members.setForeground(new java.awt.Color(170,231,37));
    }//GEN-LAST:event_membersMouseExited

    private void membersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_membersMouseEntered
        members.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_membersMouseEntered

    private void membersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_membersMouseClicked
        Memberpage up = new Memberpage();
        desktopInstance.add(up).setVisible(true);
    }//GEN-LAST:event_membersMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admins;
    private javax.swing.JPanel body;
    private javax.swing.JDesktopPane desktopInstance;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel members;
    private javax.swing.JLabel trainer;
    // End of variables declaration//GEN-END:variables
}
